package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Waypoint.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Waypoint extends Point{

	public Waypoint() {
		super();
	}

	public Waypoint(Integer id, Double x, Double y, Double z) {
		super(id, x, y, z);
	}
	
}
