package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ApSet.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class ApSet {
	private Integer fingerprintId;
	private Integer apId;
	private Integer signalStrength;
	
	public ApSet(ApSet apSet) {
		super();
		this.fingerprintId = apSet.getFingerprintId();
		this.apId = apSet.getApId();
		this.signalStrength = apSet.getSignalStrength();
	}
	public ApSet(Integer fingerprintId, Integer apId, Integer signalStrength) {
		super();
		this.fingerprintId = fingerprintId;
		this.apId = apId;
		this.signalStrength = signalStrength;
	}
	public ApSet() {
		
	}
	public Integer getFingerprintId() {
		return fingerprintId;
	}
	public void setFingerprintId(Integer fingerprintId) {
		this.fingerprintId = fingerprintId;
	}
	public Integer getApId() {
		return apId;
	}
	public void setApId(Integer apId) {
		this.apId = apId;
	}
	public Integer getSignalStrength() {
		return signalStrength;
	}
	public void setSignalStrength(Integer signalStrength) {
		this.signalStrength = signalStrength;
	}

}
