package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Measurepoint.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Measurepoint extends Point{
	private Integer mpLinkId;
	
	public Measurepoint() {
		super();
	}
	public Measurepoint(Measurepoint mp) {
		super(mp.getId(),  mp.getX(), mp.getY(), mp.getZ());
		this.mpLinkId = mp.getMpLinkId();
	}
	public Measurepoint(Integer id, Double x, Double y, Double z, Integer mpLinkId) {
		super(id, x, y, z);
		this.mpLinkId = mpLinkId;
	}
	public Integer getMpLinkId() {
		return mpLinkId;
	}
	public void setMpLinkId(Integer mpLinkId) {
		this.mpLinkId = mpLinkId;
	}
}
