package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Link.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Link{
	private Integer id;
	private Integer startPointId;
	private Integer endPointId;
	
	public Link(Link link) {
		super();
		this.id = link.getId();
		this.startPointId = link.getStartPointId();
		this.endPointId = link.getEndPointId();
	}
	
	public Link(Integer id, Integer startPointId, Integer endPointId) {
		super();
		this.id = id;
		this.startPointId = startPointId;
		this.endPointId = endPointId;
	}
	public Link() {
		
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getStartPointId() {
		return startPointId;
	}
	public void setStartPointId(Integer startPointId) {
		this.startPointId = startPointId;
	}
	public Integer getEndPointId() {
		return endPointId;
	}
	public void setEndPointId(Integer endPointId) {
		this.endPointId = endPointId;
	}

}
