package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
import java.sql.Timestamp;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fingerprint.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Fingerprint {
	private Integer id;
	private Timestamp time;
	private Double x;
	private Double y;
	private Double z;
	
	public Fingerprint(Integer id, Timestamp time, Double x, Double y, Double z) {
		this.id = id;
		this.time = time;
		this.x = x;
		this.y = y;
		this.z = z;
	}
	
	public Fingerprint() {
		
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Timestamp getTime() {
		return time;
	}
	public void setTime(Timestamp time) {
		this.time = time;
	}

	public Double getX() {
		return x;
	}

	public void setX(Double x) {
		this.x = x;
	}

	public Double getY() {
		return y;
	}

	public void setY(Double y) {
		this.y = y;
	}

	public Double getZ() {
		return z;
	}

	public void setZ(Double z) {
		this.z = z;
	}

}
