package kr.softwaremaestro.indoor.wrm.vo;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Accesspoint.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Accesspoint {
	private Integer id;
	private String bssid;
	private String ssid;
	private String capabilities;
	private Integer frequency;
	
	public Accesspoint(Accesspoint ap) {
		this(ap.getId(), ap.getBssid(), ap.getSsid(), ap.getCapabilities(), ap.getFrequency());
	}
	
	public Accesspoint(Integer id, String bssid, String ssid,
			String capabilities, Integer frequency) {
		super();
		this.id = id;
		this.bssid = bssid;
		this.ssid = ssid;
		this.capabilities = capabilities;
		this.frequency = frequency;
	}
	
	public Accesspoint() {
		
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getBssid() {
		return bssid;
	}
	public void setBssid(String bssid) {
		this.bssid = bssid;
	}
	public String getSsid() {
		return ssid;
	}
	public void setSsid(String ssid) {
		this.ssid = ssid;
	}
	public String getCapabilities() {
		return capabilities;
	}
	public void setCapabilities(String capabilities) {
		this.capabilities = capabilities;
	}
	public Integer getFrequency() {
		return frequency;
	}
	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

}
