package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BaseMeasurepoint.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class BaseMeasurepoint extends Point {
	
	public BaseMeasurepoint(BaseMeasurepoint bmp) {
		super(bmp.getId(), bmp.getX(), bmp.getY(), bmp.getZ());
	}
	public BaseMeasurepoint() {
		super();
	}
	public BaseMeasurepoint(Integer id, Double x, Double y, Double z) {
		super(id, x, y, z);
	}

}
