package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WaypointLink.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class WaypointLink extends Link{

	public WaypointLink() {
		super();
	}
	public WaypointLink(WaypointLink wayLink) {
		super(wayLink.getId(), wayLink.getStartPointId(), wayLink.getEndPointId());
	}
	public WaypointLink(Integer id, Integer startPointId, Integer endPointId) {
		super(id, startPointId, endPointId);
	}
	
}
