package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MeasurepointLink.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class MeasurepointLink extends Link{

	public MeasurepointLink() {
		super();
	}

	public MeasurepointLink(Integer id, Integer startPointId, Integer endPointId) {
		super(id, startPointId, endPointId);
	}
	
}
