package kr.softwaremaestro.indoor.wrm.vo;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Floor.java
//  @ Date : 2012-10-25
//  @ Author : 
//
//




public class Floor {
	private Integer id;
	private String name;
	private byte[] image;
	private Integer imageWidth;
	private Integer imageHeight;
	private Integer imageOriginX;
	private Integer imageOriginY;
	private Double imageScale;
	private Double z;
	
	public Floor(Integer id, String name, byte[] image, Integer imageWidth,
			Integer imageHeight, Integer imageOriginX, Integer imageOriginY,
			Double imageScale, Double z) {
		super();
		this.id = id;
		this.name = name;
		this.image = image;
		this.imageWidth = imageWidth;
		this.imageHeight = imageHeight;
		this.imageOriginX = imageOriginX;
		this.imageOriginY = imageOriginY;
		this.imageScale = imageScale;
		this.z = z;
	}
	public Floor() {
		
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public byte[] getImage() {
		return image;
	}
	public void setImage(byte[] image) {
		this.image = image;
	}
	public Integer getImageWidth() {
		return imageWidth;
	}
	public void setImageWidth(Integer imageWidth) {
		this.imageWidth = imageWidth;
	}
	public Integer getImageHeight() {
		return imageHeight;
	}
	public void setImageHeight(Integer imageHeight) {
		this.imageHeight = imageHeight;
	}
	public Integer getImageOriginX() {
		return imageOriginX;
	}
	public void setImageOriginX(Integer imageOriginX) {
		this.imageOriginX = imageOriginX;
	}
	public Integer getImageOriginY() {
		return imageOriginY;
	}
	public void setImageOriginY(Integer imageOriginY) {
		this.imageOriginY = imageOriginY;
	}
	public Double getImageScale() {
		return imageScale;
	}
	public void setImageScale(Double imageScale) {
		this.imageScale = imageScale;
	}
	public Double getZ() {
		return z;
	}
	public void setZ(Double z) {
		this.z = z;
	}

}
